version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Clever/oplog-dump
    docker:
    - image: circleci/golang:1.12-stretch
    - image: mongo:3.2.20-jessie
      entrypoint: [mongod, --nojournal, --smallfiles, --replSet, TailTest]
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
    - run:
        command: cd $HOME && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
        name: Clone ci-scripts
    - checkout
    - setup_remote_docker
    - run:
        command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        name: Set up CircleCI artifacts directories
    - run:
        name: initiate mongo replset for tests
        command: |-
          # download mongo tar
          curl -O https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.20.tgz
          # extract tar
          tar -zxvf ./mongodb-linux-x86_64-3.2.20.tgz -C ~/
          # add mongo binary location to path (and preserve in BASH_ENV script for use in later steps)
          export PATH=~/mongodb-linux-x86_64-3.2.20/bin:$PATH
          echo 'export PATH=~/mongodb-linux-x86_64-3.2.20/bin:$PATH' >> $BASH_ENV
          # initiate & confirm replset
          mongo --eval "rs.initiate()"
          mongo --eval "rs.status()"
    - run: make install_deps
    - run: make build
    - run:
        name: make test
        command: |-
          # ensure PATH has mongo commands
          source $BASH_ENV
          make test
    - run: $HOME/ci-scripts/circleci/docker-publish $DOCKER_USER $DOCKER_PASS "$DOCKER_EMAIL" $DOCKER_ORG
    - run: $HOME/ci-scripts/circleci/catapult-publish $CATAPULT_URL $CATAPULT_USER $CATAPULT_PASS oplog-dump
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/dapple-deploy $DAPPLE_URL $DAPPLE_USER $DAPPLE_PASS $APP_NAME clever-dev no-confirm-deploy; fi;
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/dapple-deploy $DAPPLE_URL $DAPPLE_USER $DAPPLE_PASS $APP_NAME production confirm-then-deploy; fi;
